package test.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbtest.users.id
     *
     * @mbg.generated Sun Dec 08 12:41:19 JST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbtest.users.name
     *
     * @mbg.generated Sun Dec 08 12:41:19 JST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbtest.users.id
     *
     * @return the value of mbtest.users.id
     *
     * @mbg.generated Sun Dec 08 12:41:19 JST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbtest.users.id
     *
     * @param id the value for mbtest.users.id
     *
     * @mbg.generated Sun Dec 08 12:41:19 JST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbtest.users.name
     *
     * @return the value of mbtest.users.name
     *
     * @mbg.generated Sun Dec 08 12:41:19 JST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbtest.users.name
     *
     * @param name the value for mbtest.users.name
     *
     * @mbg.generated Sun Dec 08 12:41:19 JST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}